version: "3"

services:
  mysql:
    image: mysql:5.6 
    container_name: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=admin 
    volumes:
      - "/opt/data/mysql:/var/lib/mysql"
    ports:
      - "3306:3306"
  redis:
    image: redis:5.0.8 
    container_name: redis 
    ports:
      - "6379:6379"
  etcd:
    image: gcr.io/etcd-development/etcd:v3.4.6
    container_name: etcd
    environment:
      - ETCD_NAME=s1
      - ETCD_DATA_DIR=/etcd-data
      - ETCD_LISTEN_PEER_URLS=http://0.0.0.0:2380
      - ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379
      - ETCD_ADVERTISE_CLIENT_URLS=http://0.0.0.0:2379
      - ETCD_INITIAL_ADVERTISE_PEER_URLS=http://0.0.0.0:2380
      - ETCD_INITIAL_CLUSTER=s1=http://0.0.0.0:2380
      - ETCD_INITIAL_CLUSTER_TOKEN=tkn
      - ETCD_INITIAL_CLUSTER_STATE=new
    command: /usr/local/bin/etcd
    volumes:
      - "/opt/data/etcd:/etcd-data"
    ports:
      - "2379:2379"
      - "2380:2380"
  mongo:
    image: mongo:4.2
    container_name: mongo 
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: admin 
    volumes:
      - "/opt/data/mongo:/data/db"
    ports:
      - "27017:27017"
